access-token:
  private: "access-refresh-token-keys/access-token-private.key"
  public: "access-refresh-token-keys/access-token-public.key"

refresh-token:
  private: "access-refresh-token-keys/refresh-token-private.key"
  public: "access-refresh-token-keys/refresh-token-public.key"

spring:
  data:
    mongodb:
      uri: "mongodb+srv://udana:123@databaseslt.gj28k.mongodb.net/test2?retryWrites=true&w=majority&appName=DatabaseSLT"
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: "818713698356-o743s2vh3ldchim1odjhuiemnjrtcfkp.apps.googleusercontent.com"
            client-secret: "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"
            scope:
              - email
              - profile

logging:
  level:
    org.springframework.security: DEBUG

server:
  port: 8080

app:
  jwt:
    secret: "YOUR_JWT_SECRET_KEY_SHOULD_BE_AT_LEAST_64_CHARACTERS_LONG"
    expiration: 86400000
