access-token:
  private: "access-refresh-token-keys/access-token-private.key"
  public: "access-refresh-token-keys/access-token-public.key"

refresh-token:
  private: "access-refresh-token-keys/refresh-token-private.key"
  public: "access-refresh-token-keys/refresh-token-public.key"

spring:
  data:
    mongodb:
      uri: mongodb+srv://udana:123@databaseslt.gj28k.mongodb.net/test2?retryWrites=true&w=majority&appName=DatabaseSLT

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: YOUR_GOOGLE_CLIENT_ID
            client-secret: YOUR_GOOGLE_CLIENT_SECRET
            scope: openid, profile, email

logging:
  level:
    org.springframework.security: DEBUG
